default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <%= ENV.fetch("DB_USER") { 'user' } %>
  password: <%= ENV.fetch("DB_PASS") { 'password' } %>
  host: <%= ENV.fetch("DB_HOST") { 'localhost' } %>
  port: <%= ENV.fetch("DB_PORT") { 3306 } %>

development:
  <<: *default
  database: <%= ENV['DB_NAME'] %>

test:
  <<: *default
  database: <%= ENV['DB_NAME'] %>

production:
  <<: *default
  database: <%= ENV['DB_NAME'] %>
