version: "3"
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
      MYSQL_USER: master
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    ports:
      - 3306:3306
    depends_on:
      - fluentd
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        tag: "docker.${NR_APP_NAME}.{{.Name}}.{{.ID}}"

  webap:
    build: 
      context: "./webap"
      args:
        - NR_APP_NAME=${NR_APP_NAME}
        - NR_LICENSEKEY=${NR_LICENSEKEY}
    container_name: webap
    environment:
      DBURL: jdbc:mysql://mysql/db
      DBUSER: master
      DBPASS: password
    ports:
      - 8080:8080
    depends_on:
      - mysql
      - fluentd
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        tag: "docker.${NR_APP_NAME}.{{.Name}}.{{.ID}}"

  fluentd:
    build: "./fluentd"
    container_name: fluentd
    ports:
      - "24224:24224"
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        tag: "docker.${NR_APP_NAME}.{{.Name}}.{{.ID}}"

