# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VariousPattern' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VariousPattern
  pod 'NewRelicAgent' #Latest
  #pod 'NewRelicAgent', '5.14.2'

  target 'VariousPatternTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'VariousPatternUITests' do
    # Pods for testing
  end

end
