version: '3'
services:
  db:
    image: mysql:5.7
    container_name: app_settings_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}      
      TZ: 'Asia/Tokyo'
    ports:
      - 3306:3306

  web:
    build:
      context: .
      dockerfile: "./resources/app_settings/Dockerfile"
    container_name: app_settings_web
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS} 
    ports:
      - "3000:3000"
    links:
      - db