version: "3"
services:
## Fargate doesn't support fluentd as log driver without firelens
#  fluentd:
#    build: "./resources/fluentd"
#    image: ${REPOSITORY_URI_PATH}nrlabs-03-petclinic-ecs-fluentd
#    container_name: fluentd
#    ports:
#      - "24224:24224"
#   volumes:
#     - /logs/webap
#   logging:
#     driver: fluentd
#     options:
#       fluentd-address: "localhost:24224"
#       tag: "docker.${NR_APP_NAME}.{{.Name}}.{{.ID}}"
#       fluentd-async-connect: "true"

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: 'Asia/Tokyo'
    ports:
      - 3306:3306
## Fargate doesn't support fluentd as log driver without firelens
#    logging:
#      driver: fluentd
#      options:
#        fluentd-address: "localhost:24224"
#        tag: "docker.${NR_APP_NAME}.{{.Name}}.{{.ID}}"
#        fluentd-async-connect: "true"        

  webap:
    build: 
      context: "./resources/webap"
      args:
        - NR_APP_NAME=${NR_APP_NAME}
        - NR_LICENSEKEY=${NR_LICENSEKEY}
    image: ${REPOSITORY_URI_PATH}nrlabs-03-petclinic-ecs-webap
    container_name: webap
    environment:
      DBURL: jdbc:mysql://localhost/${MYSQL_DATABASE}
      DBUSER: ${MYSQL_USER}
      DBPASS: ${MYSQL_PASSWORD}
    ports:
      - 8080:8080
## Fargate doesn't support fluentd as log driver without firelens
#    volumes:
#      - /logs
#    logging:
#      driver: fluentd
#      options:
#        fluentd-address: "localhost:24224"
#        tag: "docker.${NR_APP_NAME}.{{.Name}}.{{.ID}}"
#        fluentd-async-connect: "true"        
