apiVersion: batch/v1
kind: Job
metadata:
  name: ${NR_APP_NAME}-initdb
spec:
  completions: 1
  parallelism: 1
  template:
    spec:
      containers:
      - name: ${NR_APP_NAME}-initdb
        image: ${REPOSITORY_URI_PATH}${NR_APP_NAME}-web
        envFrom:
        - configMapRef:
            name: ${NR_APP_NAME}-config
        command: ["rails", "db:migrate:reset"]
      restartPolicy: Never
