version: '3'
services:
  web:
    build:
      context: .
      dockerfile: "./resources/app_settings/Dockerfile"
    image: ${REPOSITORY_URI_PATH}${NR_APP_NAME}-web
    container_name: ${NR_APP_NAME}-web
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS} 
    ports:
      - "3000:3000"
